#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Beacon",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_PROTOCOL("_TtP6Beacon26AuthRequestBuilderProtocol_")
@protocol AuthRequestBuilderProtocol
@optional
- (NSURLRequest * _Nullable)requestForSocketID:(NSString * _Nonnull)socketID channelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
@end

@class PusherAuth;

SWIFT_PROTOCOL("_TtP6Beacon10Authorizer_")
@protocol Authorizer
- (void)fetchAuthValueWithSocketID:(NSString * _Nonnull)socketID channelName:(NSString * _Nonnull)channelName completionHandler:(void (^ _Nonnull)(PusherAuth * _Nullable))completionHandler;
@end

@class HSBeaconTintColor;
@protocol HSBeaconStringLocalizer;
@class HSBeaconConfig;
@protocol HSBeaconChatEndedDelegate;
@class HSBeaconAgent;
@class HSBeaconPushNotificationSupport;

SWIFT_CLASS("_TtC6Beacon16ChatDependencies")
@interface ChatDependencies : NSObject
+ (void)setTintColorSettings:(HSBeaconTintColor * _Nonnull)tintColor;
+ (void)setStringLocalizer:(id <HSBeaconStringLocalizer> _Nonnull)stringLocalizer;
+ (void)setBeaconConfig:(HSBeaconConfig * _Nonnull)config;
+ (void)setBeaconID:(NSString * _Nonnull)beaconID;
+ (void)setDeviceID:(NSString * _Nonnull)deviceID;
+ (void)setChatEndedDelegate:(id <HSBeaconChatEndedDelegate> _Nullable)delegate;
+ (void)setBeaconAgents:(NSArray<HSBeaconAgent *> * _Nonnull)agents;
+ (void)setEnablePreviousMessages:(BOOL)enabled;
+ (void)setAttachmentsEnabled:(BOOL)enabled;
+ (void)setPushNotficationSupport:(HSBeaconPushNotificationSupport * _Nonnull)support;
+ (BOOL)hasPausedChat SWIFT_WARN_UNUSED_RESULT;
+ (Class _Nonnull)chatViewControllerClass SWIFT_WARN_UNUSED_RESULT;
+ (void)endChat;
+ (BOOL)didChatGenerateConversationWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ConnectionState, open) {
  ConnectionStateConnecting = 0,
  ConnectionStateConnected = 1,
  ConnectionStateDisconnecting = 2,
  ConnectionStateDisconnected = 3,
  ConnectionStateReconnecting = 4,
};

@class NSStream;

SWIFT_CLASS("_TtC6Beacon16FoundationStream")
@interface FoundationStream : NSObject <NSStreamDelegate>
/// Delegate for the stream methods. Processes incoming bytes
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PusherConnection;
@class PusherEvent;

SWIFT_CLASS("_TtC6Beacon13PusherChannel")
@interface PusherChannel : NSObject
@property (nonatomic) BOOL subscribed;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, weak) PusherConnection * _Nullable connection;
@property (nonatomic, strong) PusherAuth * _Nullable auth;
/// Initializes a new PusherChannel with a given name and conenction
/// \param name The name of the channel
///
/// \param connection The connection that this channel is relevant to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
///
/// returns:
/// A new PusherChannel instance
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth OBJC_DESIGNATED_INITIALIZER;
/// Binds a callback to a given event name, scoped to the PusherChannel the function is
/// called on
/// \param eventName The name of the event to bind to
///
/// \param callback The function to call when a new event is received. The
/// callback receives the event’s data payload
///
///
/// returns:
/// A unique callbackId that can be used to unbind the callback at a later time
- (NSString * _Nonnull)bindWithEventName:(NSString * _Nonnull)eventName callback:(void (^ _Nonnull)(id _Nullable))callback;
/// Binds a callback to a given event name, scoped to the PusherChannel the function is
/// called on
/// \param eventName The name of the event to bind to
///
/// \param eventCallback The function to call when a new event is received. The callback
/// receives a PusherEvent, containing the event’s data payload and
/// other properties.
///
///
/// returns:
/// A unique callbackId that can be used to unbind the callback at a later time
- (NSString * _Nonnull)bindWithEventName:(NSString * _Nonnull)eventName eventCallback:(void (^ _Nonnull)(PusherEvent * _Nonnull))eventCallback;
/// Unbinds the callback with the given callbackId from the given eventName, in the scope
/// of the channel being acted upon
/// \param eventName The name of the event from which to unbind
///
/// \param callbackId The unique callbackId string used to identify which callback to unbind
///
- (void)unbindWithEventName:(NSString * _Nonnull)eventName callbackId:(NSString * _Nonnull)callbackId;
/// Unbinds all callbacks from the channel
- (void)unbindAll;
/// Unbinds all callbacks for the given eventName from the channel
/// \param eventName The name of the event from which to unbind
///
- (void)unbindAllForEventName:(NSString * _Nonnull)eventName;
/// Calls the appropriate callbacks for the given eventName in the scope of the acted upon channel
/// \param event The event received from the websocket
///
- (void)handleEventWithEvent:(PusherEvent * _Nonnull)event;
/// If subscribed, immediately call the connection to trigger a client event with the given
/// eventName and data, otherwise queue it up to be triggered upon successful subscription
/// \param eventName The name of the event to trigger
///
/// \param data The data to be sent as the message payload
///
- (void)triggerWithEventName:(NSString * _Nonnull)eventName data:(id _Nonnull)data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Beacon13GlobalChannel")
@interface GlobalChannel : PusherChannel
/// Unbinds all callbacks from the channel
- (void)unbindAll;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth SWIFT_UNAVAILABLE;
@end

@protocol HSEnterEmailViewControllerDelegate;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC6Beacon26HSEnterEmailViewController")
@interface HSEnterEmailViewController : UIViewController
@property (nonatomic, weak) id <HSEnterEmailViewControllerDelegate> _Nullable delegate;
+ (HSEnterEmailViewController * _Nonnull)instantiateViewController SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6Beacon34HSEnterEmailViewControllerDelegate_")
@protocol HSEnterEmailViewControllerDelegate
- (void)enterEmailController:(HSEnterEmailViewController * _Nonnull)controller didEnter:(NSString * _Nonnull)email;
@end






SWIFT_CLASS("_TtC6Beacon12OCAuthMethod")
@interface OCAuthMethod : NSObject
- (nonnull instancetype)initWithType:(NSInteger)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthEndpoint:(NSString * _Nonnull)authEndpoint OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthRequestBuilder:(id <AuthRequestBuilderProtocol> _Nonnull)authRequestBuilder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSecret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthorizer:(id <Authorizer> _Nonnull)authorizer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Beacon12OCPusherHost")
@interface OCPusherHost : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHost:(NSString * _Nonnull)host OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCluster:(NSString * _Nonnull)cluster OBJC_DESIGNATED_INITIALIZER;
@end

@protocol PusherDelegate;
@class PusherClientOptions;
@class PusherPresenceChannelMember;
@class PusherPresenceChannel;

SWIFT_CLASS("_TtC6Beacon6Pusher")
@interface Pusher : NSObject
@property (nonatomic, readonly, strong) PusherConnection * _Nonnull connection;
@property (nonatomic, weak) id <PusherDelegate> _Nullable delegate;
/// Initializes the Pusher client with an app key and any appropriate options.
/// \param key The Pusher app key
///
/// \param options An optional collection of options
///
///
/// returns:
/// A new Pusher client instance
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key options:(PusherClientOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
/// Subscribes the client to a new channel
/// \param channelName The name of the channel to subscribe to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
/// \param onMemberAdded A function that will be called with information about the
/// member who has just joined the presence channel
///
/// \param onMemberRemoved A function that will be called with information about the
/// member who has just left the presence channel
///
///
/// returns:
/// A new PusherChannel instance
- (PusherChannel * _Nonnull)subscribe:(NSString * _Nonnull)channelName auth:(PusherAuth * _Nullable)auth onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
/// Subscribes the client to a new presence channel. Use this instead of the subscribe
/// function when you want a presence channel object to be returned instead of just a
/// generic channel object (which you can then cast)
/// \param channelName The name of the channel to subscribe to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
/// \param onMemberAdded A function that will be called with information about the
/// member who has just joined the presence channel
///
/// \param onMemberRemoved A function that will be called with information about the
/// member who has just left the presence channel
///
///
/// returns:
/// A new PusherPresenceChannel instance
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName auth:(PusherAuth * _Nullable)auth onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
/// Unsubscribes the client from a given channel
/// \param channelName The name of the channel to unsubscribe from
///
- (void)unsubscribe:(NSString * _Nonnull)channelName;
/// Unsubscribes the client from all channels
- (void)unsubscribeAll;
/// Binds the client’s global channel to all events
/// \param callback The function to call when a new event is received. The callback
/// receives the event’s data payload
///
///
/// returns:
/// A unique string that can be used to unbind the callback from the client
- (NSString * _Nonnull)bind:(void (^ _Nonnull)(id _Nullable))callback;
/// Binds the client’s global channel to all events
/// \param eventCallback The function to call when a new event is received. The callback
/// receives a PusherEvent, containing the event’s data payload and
/// other properties.
///
///
/// returns:
/// A unique string that can be used to unbind the callback from the client
- (NSString * _Nonnull)bindWithEventCallback:(void (^ _Nonnull)(PusherEvent * _Nonnull))eventCallback;
/// Unbinds the client from its global channel
/// \param callbackId The unique callbackId string used to identify which callback
/// to unbind
///
- (void)unbindWithCallbackId:(NSString * _Nonnull)callbackId;
/// Unbinds the client from all global callbacks
- (void)unbindAll;
/// Disconnects the client’s connection
- (void)disconnect;
/// Initiates a connection attempt using the client’s existing connection details
- (void)connect;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface Pusher (SWIFT_EXTENSION(Beacon))
- (PusherChannel * _Nonnull)subscribeWithChannelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
- (PusherChannel * _Nonnull)subscribeWithChannelName:(NSString * _Nonnull)channelName onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)key options:(PusherClientOptions * _Nonnull)options;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key;
@end


SWIFT_CLASS("_TtC6Beacon10PusherAuth")
@interface PusherAuth : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Beacon14PusherChannels")
@interface PusherChannels : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, PusherChannel *> * _Nonnull channels;
/// Return the PusherChannel with the given channelName from the channels list, if it exists
/// \param name The name of the channel to return
///
///
/// returns:
/// A PusherChannel instance, if a channel with the given name existed, otherwise nil
- (PusherChannel * _Nullable)findWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Return the PusherPresenceChannel with the given channelName from the channels list, if it exists
/// \param name The name of the presence channel to return
///
///
/// returns:
/// A PusherPresenceChannel instance, if a channel with the given name existed,
/// otherwise nil
- (PusherPresenceChannel * _Nullable)findPresenceWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Beacon19PusherClientOptions")
@interface PusherClientOptions : NSObject
@property (nonatomic, readonly) BOOL attemptToReturnJSONObject;
@property (nonatomic, readonly) BOOL autoReconnect;
@property (nonatomic, readonly, copy) NSString * _Nonnull host;
@property (nonatomic, readonly) NSInteger port;
@property (nonatomic, readonly) BOOL useTLS;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

@interface PusherClientOptions (SWIFT_EXTENSION(Beacon))
- (nonnull instancetype)initWithOcAuthMethod:(OCAuthMethod * _Nonnull)authMethod autoReconnect:(BOOL)autoReconnect ocHost:(OCPusherHost * _Nonnull)host port:(NSNumber * _Nullable)port useTLS:(BOOL)useTLS activityTimeout:(NSNumber * _Nullable)activityTimeout;
- (nonnull instancetype)initWithOcAuthMethod:(OCAuthMethod * _Nonnull)authMethod attemptToReturnJSONObject:(BOOL)attemptToReturnJSONObject autoReconnect:(BOOL)autoReconnect ocHost:(OCPusherHost * _Nonnull)host port:(NSNumber * _Nullable)port useTLS:(BOOL)useTLS activityTimeout:(NSNumber * _Nullable)activityTimeout;
- (nonnull instancetype)initWithAuthMethod:(OCAuthMethod * _Nonnull)authMethod;
- (void)setAuthMethodWithAuthMethod:(OCAuthMethod * _Nonnull)authMethod;
@end

@class WebSocket;
@class NSURLSession;
@class PusherError;

SWIFT_CLASS("_TtC6Beacon16PusherConnection")
@interface PusherConnection : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic, strong) PusherClientOptions * _Nonnull options;
@property (nonatomic, strong) GlobalChannel * _Null_unspecified globalChannel;
@property (nonatomic, copy) NSString * _Nullable socketId;
@property (nonatomic) enum ConnectionState connectionState;
@property (nonatomic, strong) PusherChannels * _Nonnull channels;
@property (nonatomic, strong) WebSocket * _Null_unspecified socket;
@property (nonatomic, strong) NSURLSession * _Nonnull URLSession;
@property (nonatomic, copy) PusherPresenceChannelMember * _Nonnull (^ _Nullable userDataFetcher)(void);
@property (nonatomic) NSInteger reconnectAttempts;
@property (nonatomic, weak) id <PusherDelegate> _Nullable delegate;
@property (nonatomic) NSTimeInterval pongResponseTimeoutInterval;
@property (nonatomic) NSTimeInterval activityTimeoutInterval;
/// Initializes a new PusherConnection with an app key, websocket, URL, options and URLSession
/// \param key The Pusher app key
///
/// \param socket The websocket object
///
/// \param url The URL the connection is made to
///
/// \param options A PusherClientOptions instance containing all of the user-speficied
/// client options
///
/// \param URLSession An NSURLSession instance for the connection to use for making
/// authentication requests
///
///
/// returns:
/// A new PusherConnection instance
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key socket:(WebSocket * _Nonnull)socket url:(NSString * _Nonnull)url options:(PusherClientOptions * _Nonnull)options URLSession:(NSURLSession * _Nonnull)URLSession OBJC_DESIGNATED_INITIALIZER;
/// Either writes a string directly to the websocket with the given event name
/// and data, or calls a client event to be sent if the event is prefixed with
/// “client”
/// \param event The name of the event
///
/// \param data The data to be stringified and sent
///
/// \param channel The name of the channel
///
- (void)sendEventWithEvent:(NSString * _Nonnull)event data:(id _Nonnull)data channel:(PusherChannel * _Nullable)channel;
/// Disconnects the websocket
- (void)disconnect;
/// Establish a websocket connection
- (void)connect;
/// Handles incoming error
/// \param error The incoming error to be processed
///
- (void)handleErrorWithError:(PusherError * _Nonnull)error;
/// Handles incoming events and passes them on to be handled by the appropriate function
/// \param event The incoming event to be processed
///
- (void)handleEventWithEvent:(PusherEvent * _Nonnull)event;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface PusherConnection (SWIFT_EXTENSION(Beacon))
@property (nonatomic, strong) NSNumber * _Nullable OCReconnectAttemptsMax;
@property (nonatomic, strong) NSNumber * _Nullable OCMaxReconnectGapInSeconds;
@end





@class NSURLResponse;
@class NSError;

SWIFT_PROTOCOL("_TtP6Beacon14PusherDelegate_")
@protocol PusherDelegate
@optional
- (void)debugLogWithMessage:(NSString * _Nonnull)message;
- (void)changedConnectionStateFrom:(enum ConnectionState)old to:(enum ConnectionState)new_;
- (void)subscribedToChannelWithName:(NSString * _Nonnull)name;
- (void)failedToSubscribeToChannelWithName:(NSString * _Nonnull)name response:(NSURLResponse * _Nullable)response data:(NSString * _Nullable)data error:(NSError * _Nullable)error;
- (void)failedToDecryptEventWithEventName:(NSString * _Nonnull)eventName channelName:(NSString * _Nonnull)channelName data:(NSString * _Nullable)data;
- (void)receivedError:(PusherError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC6Beacon11PusherError")
@interface PusherError : NSObject
/// The error message.
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface PusherError (SWIFT_EXTENSION(Beacon))
/// The error code as an NSNumber (for Objective-C compatibility).
@property (nonatomic, readonly, strong) NSNumber * _Nullable codeOC;
@end


SWIFT_CLASS("_TtC6Beacon11PusherEvent")
@interface PusherEvent : NSObject <NSCopying>
/// The name of the event.
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
/// The name of the channel that the event was triggered on. Not present in events without an associated channel, e.g. “pusher:error” events relating to the connection.
@property (nonatomic, readonly, copy) NSString * _Nullable channelName;
/// The data that was passed when the event was triggered.
@property (nonatomic, readonly, copy) NSString * _Nullable data;
/// The ID of the user who triggered the event. Only present in client event on presence channels.
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
/// A helper function for accessing raw properties from the websocket event. Data
/// returned by this function should not be considered stable and it is recommended
/// that you use the properties of the <code>PusherEvent</code> instance instead e.g.
/// <code>eventName</code>, <code>channelName</code> etc.
/// \param key The key of the property to be returned
///
///
/// returns:
/// The property, if present
- (id _Nullable)propertyWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Beacon21PusherPresenceChannel")
@interface PusherPresenceChannel : PusherChannel
@property (nonatomic, copy) NSArray<PusherPresenceChannelMember *> * _Nonnull members;
@property (nonatomic, copy) void (^ _Nullable onMemberAdded)(PusherPresenceChannelMember * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onMemberRemoved)(PusherPresenceChannelMember * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable myId;
/// Returns the PusherPresenceChannelMember object for the given user id
/// \param userId The user id of the PusherPresenceChannelMember for whom you want
/// the PusherPresenceChannelMember object
///
///
/// returns:
/// The PusherPresenceChannelMember object for the given user id
- (PusherPresenceChannelMember * _Nullable)findMemberWithUserId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
/// Returns the connected user’s PusherPresenceChannelMember object
///
/// returns:
/// The connected user’s PusherPresenceChannelMember object
- (PusherPresenceChannelMember * _Nullable)me SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Beacon27PusherPresenceChannelMember")
@interface PusherPresenceChannelMember : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly) id _Nullable userInfo;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId userInfo:(id _Nullable)userInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
















SWIFT_CLASS("_TtC6Beacon9WebSocket")
@interface WebSocket : NSObject <NSStreamDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#else
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Beacon",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_PROTOCOL("_TtP6Beacon26AuthRequestBuilderProtocol_")
@protocol AuthRequestBuilderProtocol
@optional
- (NSURLRequest * _Nullable)requestForSocketID:(NSString * _Nonnull)socketID channelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
@end

@class PusherAuth;

SWIFT_PROTOCOL("_TtP6Beacon10Authorizer_")
@protocol Authorizer
- (void)fetchAuthValueWithSocketID:(NSString * _Nonnull)socketID channelName:(NSString * _Nonnull)channelName completionHandler:(void (^ _Nonnull)(PusherAuth * _Nullable))completionHandler;
@end

@class HSBeaconTintColor;
@protocol HSBeaconStringLocalizer;
@class HSBeaconConfig;
@protocol HSBeaconChatEndedDelegate;
@class HSBeaconAgent;
@class HSBeaconPushNotificationSupport;

SWIFT_CLASS("_TtC6Beacon16ChatDependencies")
@interface ChatDependencies : NSObject
+ (void)setTintColorSettings:(HSBeaconTintColor * _Nonnull)tintColor;
+ (void)setStringLocalizer:(id <HSBeaconStringLocalizer> _Nonnull)stringLocalizer;
+ (void)setBeaconConfig:(HSBeaconConfig * _Nonnull)config;
+ (void)setBeaconID:(NSString * _Nonnull)beaconID;
+ (void)setDeviceID:(NSString * _Nonnull)deviceID;
+ (void)setChatEndedDelegate:(id <HSBeaconChatEndedDelegate> _Nullable)delegate;
+ (void)setBeaconAgents:(NSArray<HSBeaconAgent *> * _Nonnull)agents;
+ (void)setEnablePreviousMessages:(BOOL)enabled;
+ (void)setAttachmentsEnabled:(BOOL)enabled;
+ (void)setPushNotficationSupport:(HSBeaconPushNotificationSupport * _Nonnull)support;
+ (BOOL)hasPausedChat SWIFT_WARN_UNUSED_RESULT;
+ (Class _Nonnull)chatViewControllerClass SWIFT_WARN_UNUSED_RESULT;
+ (void)endChat;
+ (BOOL)didChatGenerateConversationWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ConnectionState, open) {
  ConnectionStateConnecting = 0,
  ConnectionStateConnected = 1,
  ConnectionStateDisconnecting = 2,
  ConnectionStateDisconnected = 3,
  ConnectionStateReconnecting = 4,
};

@class NSStream;

SWIFT_CLASS("_TtC6Beacon16FoundationStream")
@interface FoundationStream : NSObject <NSStreamDelegate>
/// Delegate for the stream methods. Processes incoming bytes
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PusherConnection;
@class PusherEvent;

SWIFT_CLASS("_TtC6Beacon13PusherChannel")
@interface PusherChannel : NSObject
@property (nonatomic) BOOL subscribed;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, weak) PusherConnection * _Nullable connection;
@property (nonatomic, strong) PusherAuth * _Nullable auth;
/// Initializes a new PusherChannel with a given name and conenction
/// \param name The name of the channel
///
/// \param connection The connection that this channel is relevant to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
///
/// returns:
/// A new PusherChannel instance
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth OBJC_DESIGNATED_INITIALIZER;
/// Binds a callback to a given event name, scoped to the PusherChannel the function is
/// called on
/// \param eventName The name of the event to bind to
///
/// \param callback The function to call when a new event is received. The
/// callback receives the event’s data payload
///
///
/// returns:
/// A unique callbackId that can be used to unbind the callback at a later time
- (NSString * _Nonnull)bindWithEventName:(NSString * _Nonnull)eventName callback:(void (^ _Nonnull)(id _Nullable))callback;
/// Binds a callback to a given event name, scoped to the PusherChannel the function is
/// called on
/// \param eventName The name of the event to bind to
///
/// \param eventCallback The function to call when a new event is received. The callback
/// receives a PusherEvent, containing the event’s data payload and
/// other properties.
///
///
/// returns:
/// A unique callbackId that can be used to unbind the callback at a later time
- (NSString * _Nonnull)bindWithEventName:(NSString * _Nonnull)eventName eventCallback:(void (^ _Nonnull)(PusherEvent * _Nonnull))eventCallback;
/// Unbinds the callback with the given callbackId from the given eventName, in the scope
/// of the channel being acted upon
/// \param eventName The name of the event from which to unbind
///
/// \param callbackId The unique callbackId string used to identify which callback to unbind
///
- (void)unbindWithEventName:(NSString * _Nonnull)eventName callbackId:(NSString * _Nonnull)callbackId;
/// Unbinds all callbacks from the channel
- (void)unbindAll;
/// Unbinds all callbacks for the given eventName from the channel
/// \param eventName The name of the event from which to unbind
///
- (void)unbindAllForEventName:(NSString * _Nonnull)eventName;
/// Calls the appropriate callbacks for the given eventName in the scope of the acted upon channel
/// \param event The event received from the websocket
///
- (void)handleEventWithEvent:(PusherEvent * _Nonnull)event;
/// If subscribed, immediately call the connection to trigger a client event with the given
/// eventName and data, otherwise queue it up to be triggered upon successful subscription
/// \param eventName The name of the event to trigger
///
/// \param data The data to be sent as the message payload
///
- (void)triggerWithEventName:(NSString * _Nonnull)eventName data:(id _Nonnull)data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Beacon13GlobalChannel")
@interface GlobalChannel : PusherChannel
/// Unbinds all callbacks from the channel
- (void)unbindAll;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth SWIFT_UNAVAILABLE;
@end

@protocol HSEnterEmailViewControllerDelegate;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC6Beacon26HSEnterEmailViewController")
@interface HSEnterEmailViewController : UIViewController
@property (nonatomic, weak) id <HSEnterEmailViewControllerDelegate> _Nullable delegate;
+ (HSEnterEmailViewController * _Nonnull)instantiateViewController SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6Beacon34HSEnterEmailViewControllerDelegate_")
@protocol HSEnterEmailViewControllerDelegate
- (void)enterEmailController:(HSEnterEmailViewController * _Nonnull)controller didEnter:(NSString * _Nonnull)email;
@end






SWIFT_CLASS("_TtC6Beacon12OCAuthMethod")
@interface OCAuthMethod : NSObject
- (nonnull instancetype)initWithType:(NSInteger)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthEndpoint:(NSString * _Nonnull)authEndpoint OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthRequestBuilder:(id <AuthRequestBuilderProtocol> _Nonnull)authRequestBuilder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSecret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAuthorizer:(id <Authorizer> _Nonnull)authorizer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6Beacon12OCPusherHost")
@interface OCPusherHost : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithHost:(NSString * _Nonnull)host OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCluster:(NSString * _Nonnull)cluster OBJC_DESIGNATED_INITIALIZER;
@end

@protocol PusherDelegate;
@class PusherClientOptions;
@class PusherPresenceChannelMember;
@class PusherPresenceChannel;

SWIFT_CLASS("_TtC6Beacon6Pusher")
@interface Pusher : NSObject
@property (nonatomic, readonly, strong) PusherConnection * _Nonnull connection;
@property (nonatomic, weak) id <PusherDelegate> _Nullable delegate;
/// Initializes the Pusher client with an app key and any appropriate options.
/// \param key The Pusher app key
///
/// \param options An optional collection of options
///
///
/// returns:
/// A new Pusher client instance
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key options:(PusherClientOptions * _Nonnull)options OBJC_DESIGNATED_INITIALIZER;
/// Subscribes the client to a new channel
/// \param channelName The name of the channel to subscribe to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
/// \param onMemberAdded A function that will be called with information about the
/// member who has just joined the presence channel
///
/// \param onMemberRemoved A function that will be called with information about the
/// member who has just left the presence channel
///
///
/// returns:
/// A new PusherChannel instance
- (PusherChannel * _Nonnull)subscribe:(NSString * _Nonnull)channelName auth:(PusherAuth * _Nullable)auth onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
/// Subscribes the client to a new presence channel. Use this instead of the subscribe
/// function when you want a presence channel object to be returned instead of just a
/// generic channel object (which you can then cast)
/// \param channelName The name of the channel to subscribe to
///
/// \param auth A PusherAuth value if subscription is being made to an
/// authenticated channel without using the default auth methods
///
/// \param onMemberAdded A function that will be called with information about the
/// member who has just joined the presence channel
///
/// \param onMemberRemoved A function that will be called with information about the
/// member who has just left the presence channel
///
///
/// returns:
/// A new PusherPresenceChannel instance
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName auth:(PusherAuth * _Nullable)auth onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
/// Unsubscribes the client from a given channel
/// \param channelName The name of the channel to unsubscribe from
///
- (void)unsubscribe:(NSString * _Nonnull)channelName;
/// Unsubscribes the client from all channels
- (void)unsubscribeAll;
/// Binds the client’s global channel to all events
/// \param callback The function to call when a new event is received. The callback
/// receives the event’s data payload
///
///
/// returns:
/// A unique string that can be used to unbind the callback from the client
- (NSString * _Nonnull)bind:(void (^ _Nonnull)(id _Nullable))callback;
/// Binds the client’s global channel to all events
/// \param eventCallback The function to call when a new event is received. The callback
/// receives a PusherEvent, containing the event’s data payload and
/// other properties.
///
///
/// returns:
/// A unique string that can be used to unbind the callback from the client
- (NSString * _Nonnull)bindWithEventCallback:(void (^ _Nonnull)(PusherEvent * _Nonnull))eventCallback;
/// Unbinds the client from its global channel
/// \param callbackId The unique callbackId string used to identify which callback
/// to unbind
///
- (void)unbindWithCallbackId:(NSString * _Nonnull)callbackId;
/// Unbinds the client from all global callbacks
- (void)unbindAll;
/// Disconnects the client’s connection
- (void)disconnect;
/// Initiates a connection attempt using the client’s existing connection details
- (void)connect;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface Pusher (SWIFT_EXTENSION(Beacon))
- (PusherChannel * _Nonnull)subscribeWithChannelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
- (PusherChannel * _Nonnull)subscribeWithChannelName:(NSString * _Nonnull)channelName onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName SWIFT_WARN_UNUSED_RESULT;
- (PusherPresenceChannel * _Nonnull)subscribeToPresenceChannelWithChannelName:(NSString * _Nonnull)channelName onMemberAdded:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberAdded onMemberRemoved:(void (^ _Nullable)(PusherPresenceChannelMember * _Nonnull))onMemberRemoved SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)key options:(PusherClientOptions * _Nonnull)options;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key;
@end


SWIFT_CLASS("_TtC6Beacon10PusherAuth")
@interface PusherAuth : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6Beacon14PusherChannels")
@interface PusherChannels : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, PusherChannel *> * _Nonnull channels;
/// Return the PusherChannel with the given channelName from the channels list, if it exists
/// \param name The name of the channel to return
///
///
/// returns:
/// A PusherChannel instance, if a channel with the given name existed, otherwise nil
- (PusherChannel * _Nullable)findWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
/// Return the PusherPresenceChannel with the given channelName from the channels list, if it exists
/// \param name The name of the presence channel to return
///
///
/// returns:
/// A PusherPresenceChannel instance, if a channel with the given name existed,
/// otherwise nil
- (PusherPresenceChannel * _Nullable)findPresenceWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6Beacon19PusherClientOptions")
@interface PusherClientOptions : NSObject
@property (nonatomic, readonly) BOOL attemptToReturnJSONObject;
@property (nonatomic, readonly) BOOL autoReconnect;
@property (nonatomic, readonly, copy) NSString * _Nonnull host;
@property (nonatomic, readonly) NSInteger port;
@property (nonatomic, readonly) BOOL useTLS;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

@interface PusherClientOptions (SWIFT_EXTENSION(Beacon))
- (nonnull instancetype)initWithOcAuthMethod:(OCAuthMethod * _Nonnull)authMethod autoReconnect:(BOOL)autoReconnect ocHost:(OCPusherHost * _Nonnull)host port:(NSNumber * _Nullable)port useTLS:(BOOL)useTLS activityTimeout:(NSNumber * _Nullable)activityTimeout;
- (nonnull instancetype)initWithOcAuthMethod:(OCAuthMethod * _Nonnull)authMethod attemptToReturnJSONObject:(BOOL)attemptToReturnJSONObject autoReconnect:(BOOL)autoReconnect ocHost:(OCPusherHost * _Nonnull)host port:(NSNumber * _Nullable)port useTLS:(BOOL)useTLS activityTimeout:(NSNumber * _Nullable)activityTimeout;
- (nonnull instancetype)initWithAuthMethod:(OCAuthMethod * _Nonnull)authMethod;
- (void)setAuthMethodWithAuthMethod:(OCAuthMethod * _Nonnull)authMethod;
@end

@class WebSocket;
@class NSURLSession;
@class PusherError;

SWIFT_CLASS("_TtC6Beacon16PusherConnection")
@interface PusherConnection : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic, strong) PusherClientOptions * _Nonnull options;
@property (nonatomic, strong) GlobalChannel * _Null_unspecified globalChannel;
@property (nonatomic, copy) NSString * _Nullable socketId;
@property (nonatomic) enum ConnectionState connectionState;
@property (nonatomic, strong) PusherChannels * _Nonnull channels;
@property (nonatomic, strong) WebSocket * _Null_unspecified socket;
@property (nonatomic, strong) NSURLSession * _Nonnull URLSession;
@property (nonatomic, copy) PusherPresenceChannelMember * _Nonnull (^ _Nullable userDataFetcher)(void);
@property (nonatomic) NSInteger reconnectAttempts;
@property (nonatomic, weak) id <PusherDelegate> _Nullable delegate;
@property (nonatomic) NSTimeInterval pongResponseTimeoutInterval;
@property (nonatomic) NSTimeInterval activityTimeoutInterval;
/// Initializes a new PusherConnection with an app key, websocket, URL, options and URLSession
/// \param key The Pusher app key
///
/// \param socket The websocket object
///
/// \param url The URL the connection is made to
///
/// \param options A PusherClientOptions instance containing all of the user-speficied
/// client options
///
/// \param URLSession An NSURLSession instance for the connection to use for making
/// authentication requests
///
///
/// returns:
/// A new PusherConnection instance
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key socket:(WebSocket * _Nonnull)socket url:(NSString * _Nonnull)url options:(PusherClientOptions * _Nonnull)options URLSession:(NSURLSession * _Nonnull)URLSession OBJC_DESIGNATED_INITIALIZER;
/// Either writes a string directly to the websocket with the given event name
/// and data, or calls a client event to be sent if the event is prefixed with
/// “client”
/// \param event The name of the event
///
/// \param data The data to be stringified and sent
///
/// \param channel The name of the channel
///
- (void)sendEventWithEvent:(NSString * _Nonnull)event data:(id _Nonnull)data channel:(PusherChannel * _Nullable)channel;
/// Disconnects the websocket
- (void)disconnect;
/// Establish a websocket connection
- (void)connect;
/// Handles incoming error
/// \param error The incoming error to be processed
///
- (void)handleErrorWithError:(PusherError * _Nonnull)error;
/// Handles incoming events and passes them on to be handled by the appropriate function
/// \param event The incoming event to be processed
///
- (void)handleEventWithEvent:(PusherEvent * _Nonnull)event;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface PusherConnection (SWIFT_EXTENSION(Beacon))
@property (nonatomic, strong) NSNumber * _Nullable OCReconnectAttemptsMax;
@property (nonatomic, strong) NSNumber * _Nullable OCMaxReconnectGapInSeconds;
@end





@class NSURLResponse;
@class NSError;

SWIFT_PROTOCOL("_TtP6Beacon14PusherDelegate_")
@protocol PusherDelegate
@optional
- (void)debugLogWithMessage:(NSString * _Nonnull)message;
- (void)changedConnectionStateFrom:(enum ConnectionState)old to:(enum ConnectionState)new_;
- (void)subscribedToChannelWithName:(NSString * _Nonnull)name;
- (void)failedToSubscribeToChannelWithName:(NSString * _Nonnull)name response:(NSURLResponse * _Nullable)response data:(NSString * _Nullable)data error:(NSError * _Nullable)error;
- (void)failedToDecryptEventWithEventName:(NSString * _Nonnull)eventName channelName:(NSString * _Nonnull)channelName data:(NSString * _Nullable)data;
- (void)receivedError:(PusherError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC6Beacon11PusherError")
@interface PusherError : NSObject
/// The error message.
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface PusherError (SWIFT_EXTENSION(Beacon))
/// The error code as an NSNumber (for Objective-C compatibility).
@property (nonatomic, readonly, strong) NSNumber * _Nullable codeOC;
@end


SWIFT_CLASS("_TtC6Beacon11PusherEvent")
@interface PusherEvent : NSObject <NSCopying>
/// The name of the event.
@property (nonatomic, readonly, copy) NSString * _Nonnull eventName;
/// The name of the channel that the event was triggered on. Not present in events without an associated channel, e.g. “pusher:error” events relating to the connection.
@property (nonatomic, readonly, copy) NSString * _Nullable channelName;
/// The data that was passed when the event was triggered.
@property (nonatomic, readonly, copy) NSString * _Nullable data;
/// The ID of the user who triggered the event. Only present in client event on presence channels.
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
/// A helper function for accessing raw properties from the websocket event. Data
/// returned by this function should not be considered stable and it is recommended
/// that you use the properties of the <code>PusherEvent</code> instance instead e.g.
/// <code>eventName</code>, <code>channelName</code> etc.
/// \param key The key of the property to be returned
///
///
/// returns:
/// The property, if present
- (id _Nullable)propertyWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS("_TtC6Beacon21PusherPresenceChannel")
@interface PusherPresenceChannel : PusherChannel
@property (nonatomic, copy) NSArray<PusherPresenceChannelMember *> * _Nonnull members;
@property (nonatomic, copy) void (^ _Nullable onMemberAdded)(PusherPresenceChannelMember * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onMemberRemoved)(PusherPresenceChannelMember * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable myId;
/// Returns the PusherPresenceChannelMember object for the given user id
/// \param userId The user id of the PusherPresenceChannelMember for whom you want
/// the PusherPresenceChannelMember object
///
///
/// returns:
/// The PusherPresenceChannelMember object for the given user id
- (PusherPresenceChannelMember * _Nullable)findMemberWithUserId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
/// Returns the connected user’s PusherPresenceChannelMember object
///
/// returns:
/// The connected user’s PusherPresenceChannelMember object
- (PusherPresenceChannelMember * _Nullable)me SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name connection:(PusherConnection * _Nonnull)connection auth:(PusherAuth * _Nullable)auth SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6Beacon27PusherPresenceChannelMember")
@interface PusherPresenceChannelMember : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
@property (nonatomic, readonly) id _Nullable userInfo;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId userInfo:(id _Nullable)userInfo OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
















SWIFT_CLASS("_TtC6Beacon9WebSocket")
@interface WebSocket : NSObject <NSStreamDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
